interface ServerConfigHandler {

    typedef sequence<string> StringSequence;
    typedef sequence<octet> ByteSequence;

    boolean loadPlugin(in string pluginId, in string pluginName);
    boolean unloadPlugin(in string pluginId);

    boolean set(in string pluginId, in string propertyName, in ByteSequence value);
    ByteSequence get(in string pluginId, in string propertyName);

    ByteSequence exec(in string pluginId, in string taskName, in ByteSequence argumentList);

    StringSequence metaProperties(in string pluginId);
    StringSequence metaTasks(in string pluginId);

    string lastErrorString();
    boolean hasFailure();

};
