// This file is generated by omniidl (C++ backend)- omniORB_4_1. Do not edit.
#ifndef __ServerConfigHandler_hh__
#define __ServerConfigHandler_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_ServerConfigHandler
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_ServerConfigHandler
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_ServerConfigHandler
#endif






#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif





#ifndef __ServerConfigHandler__
#define __ServerConfigHandler__

class ServerConfigHandler;
class _objref_ServerConfigHandler;
class _impl_ServerConfigHandler;

typedef _objref_ServerConfigHandler* ServerConfigHandler_ptr;
typedef ServerConfigHandler_ptr ServerConfigHandlerRef;

class ServerConfigHandler_Helper {
public:
  typedef ServerConfigHandler_ptr _ptr_type;

  static _ptr_type _nil();
  static _CORBA_Boolean is_nil(_ptr_type);
  static void release(_ptr_type);
  static void duplicate(_ptr_type);
  static void marshalObjRef(_ptr_type, cdrStream&);
  static _ptr_type unmarshalObjRef(cdrStream&);
};

typedef _CORBA_ObjRef_Var<_objref_ServerConfigHandler, ServerConfigHandler_Helper> ServerConfigHandler_var;
typedef _CORBA_ObjRef_OUT_arg<_objref_ServerConfigHandler,ServerConfigHandler_Helper > ServerConfigHandler_out;

#endif

// interface ServerConfigHandler
class ServerConfigHandler {
public:
  // Declarations for this interface type.
  typedef ServerConfigHandler_ptr _ptr_type;
  typedef ServerConfigHandler_var _var_type;

  static _ptr_type _duplicate(_ptr_type);
  static _ptr_type _narrow(::CORBA::Object_ptr);
  static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
  
  static _ptr_type _nil();

  static inline void _marshalObjRef(_ptr_type, cdrStream&);

  static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
    omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
    if (o)
      return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
    else
      return _nil();
  }

  static _core_attr const char* _PD_repoId;

  // Other IDL defined within this scope.
  class StringSequence_var;

  class StringSequence : public _CORBA_Unbounded_Sequence_String {
  public:
    typedef StringSequence_var _var_type;
    inline StringSequence() {}
    inline StringSequence(const StringSequence& _s)
      : _CORBA_Unbounded_Sequence_String(_s) {}

    inline StringSequence(_CORBA_ULong _max)
      : _CORBA_Unbounded_Sequence_String(_max) {}
    inline StringSequence(_CORBA_ULong _max, _CORBA_ULong _len, char** _val, _CORBA_Boolean _rel=0)
      : _CORBA_Unbounded_Sequence_String(_max, _len, _val, _rel) {}

  

    inline StringSequence& operator = (const StringSequence& _s) {
      _CORBA_Unbounded_Sequence_String::operator=(_s);
      return *this;
    }
  };

  class StringSequence_out;

  class StringSequence_var {
  public:
    inline StringSequence_var() : _pd_seq(0) {}
    inline StringSequence_var(StringSequence* _s) : _pd_seq(_s) {}
    inline StringSequence_var(const StringSequence_var& _s) {
      if( _s._pd_seq )  _pd_seq = new StringSequence(*_s._pd_seq);
      else              _pd_seq = 0;
    }
    inline ~StringSequence_var() { if( _pd_seq )  delete _pd_seq; }
      
    inline StringSequence_var& operator = (StringSequence* _s) {
      if( _pd_seq )  delete _pd_seq;
      _pd_seq = _s;
      return *this;
    }
    inline StringSequence_var& operator = (const StringSequence_var& _s) {
      if( _s._pd_seq ) {
        if( !_pd_seq )  _pd_seq = new StringSequence;
        *_pd_seq = *_s._pd_seq;
      } else if( _pd_seq ) {
        delete _pd_seq;
        _pd_seq = 0;
      }
      return *this;
    }
    inline _CORBA_String_element operator [] (_CORBA_ULong _s) {
      return (*_pd_seq)[_s];
    }

  

    inline StringSequence* operator -> () { return _pd_seq; }
    inline const StringSequence* operator -> () const { return _pd_seq; }
#if defined(__GNUG__)
    inline operator StringSequence& () const { return *_pd_seq; }
#else
    inline operator const StringSequence& () const { return *_pd_seq; }
    inline operator StringSequence& () { return *_pd_seq; }
#endif
      
    inline const StringSequence& in() const { return *_pd_seq; }
    inline StringSequence&       inout()    { return *_pd_seq; }
    inline StringSequence*&      out() {
      if( _pd_seq ) { delete _pd_seq; _pd_seq = 0; }
      return _pd_seq;
    }
    inline StringSequence* _retn() { StringSequence* tmp = _pd_seq; _pd_seq = 0; return tmp; }
      
    friend class StringSequence_out;
    
  private:
    StringSequence* _pd_seq;
  };

  class StringSequence_out {
  public:
    inline StringSequence_out(StringSequence*& _s) : _data(_s) { _data = 0; }
    inline StringSequence_out(StringSequence_var& _s)
      : _data(_s._pd_seq) { _s = (StringSequence*) 0; }
    inline StringSequence_out(const StringSequence_out& _s) : _data(_s._data) {}
    inline StringSequence_out& operator = (const StringSequence_out& _s) {
      _data = _s._data;
      return *this;
    }
    inline StringSequence_out& operator = (StringSequence* _s) {
      _data = _s;
      return *this;
    }
    inline operator StringSequence*&()  { return _data; }
    inline StringSequence*& ptr()       { return _data; }
    inline StringSequence* operator->() { return _data; }

    inline _CORBA_String_element operator [] (_CORBA_ULong _i) {
      return (*_data)[_i];
    }

  

    StringSequence*& _data;

  private:
    StringSequence_out();
    StringSequence_out& operator=(const StringSequence_var&);
  };

  class ByteSequence_var;

  class ByteSequence : public _CORBA_Unbounded_Sequence_Octet {
  public:
    typedef ByteSequence_var _var_type;
    inline ByteSequence() {}
    inline ByteSequence(const ByteSequence& _s)
      : _CORBA_Unbounded_Sequence_Octet(_s) {}

    inline ByteSequence(_CORBA_ULong _max)
      : _CORBA_Unbounded_Sequence_Octet(_max) {}
    inline ByteSequence(_CORBA_ULong _max, _CORBA_ULong _len, ::CORBA::Octet* _val, _CORBA_Boolean _rel=0)
      : _CORBA_Unbounded_Sequence_Octet(_max, _len, _val, _rel) {}

  

    inline ByteSequence& operator = (const ByteSequence& _s) {
      _CORBA_Unbounded_Sequence_Octet::operator=(_s);
      return *this;
    }
  };

  class ByteSequence_out;

  class ByteSequence_var {
  public:
    inline ByteSequence_var() : _pd_seq(0) {}
    inline ByteSequence_var(ByteSequence* _s) : _pd_seq(_s) {}
    inline ByteSequence_var(const ByteSequence_var& _s) {
      if( _s._pd_seq )  _pd_seq = new ByteSequence(*_s._pd_seq);
      else              _pd_seq = 0;
    }
    inline ~ByteSequence_var() { if( _pd_seq )  delete _pd_seq; }
      
    inline ByteSequence_var& operator = (ByteSequence* _s) {
      if( _pd_seq )  delete _pd_seq;
      _pd_seq = _s;
      return *this;
    }
    inline ByteSequence_var& operator = (const ByteSequence_var& _s) {
      if( _s._pd_seq ) {
        if( !_pd_seq )  _pd_seq = new ByteSequence;
        *_pd_seq = *_s._pd_seq;
      } else if( _pd_seq ) {
        delete _pd_seq;
        _pd_seq = 0;
      }
      return *this;
    }
    inline ::CORBA::Octet& operator [] (_CORBA_ULong _s) {
      return (*_pd_seq)[_s];
    }

  

    inline ByteSequence* operator -> () { return _pd_seq; }
    inline const ByteSequence* operator -> () const { return _pd_seq; }
#if defined(__GNUG__)
    inline operator ByteSequence& () const { return *_pd_seq; }
#else
    inline operator const ByteSequence& () const { return *_pd_seq; }
    inline operator ByteSequence& () { return *_pd_seq; }
#endif
      
    inline const ByteSequence& in() const { return *_pd_seq; }
    inline ByteSequence&       inout()    { return *_pd_seq; }
    inline ByteSequence*&      out() {
      if( _pd_seq ) { delete _pd_seq; _pd_seq = 0; }
      return _pd_seq;
    }
    inline ByteSequence* _retn() { ByteSequence* tmp = _pd_seq; _pd_seq = 0; return tmp; }
      
    friend class ByteSequence_out;
    
  private:
    ByteSequence* _pd_seq;
  };

  class ByteSequence_out {
  public:
    inline ByteSequence_out(ByteSequence*& _s) : _data(_s) { _data = 0; }
    inline ByteSequence_out(ByteSequence_var& _s)
      : _data(_s._pd_seq) { _s = (ByteSequence*) 0; }
    inline ByteSequence_out(const ByteSequence_out& _s) : _data(_s._data) {}
    inline ByteSequence_out& operator = (const ByteSequence_out& _s) {
      _data = _s._data;
      return *this;
    }
    inline ByteSequence_out& operator = (ByteSequence* _s) {
      _data = _s;
      return *this;
    }
    inline operator ByteSequence*&()  { return _data; }
    inline ByteSequence*& ptr()       { return _data; }
    inline ByteSequence* operator->() { return _data; }

    inline ::CORBA::Octet& operator [] (_CORBA_ULong _i) {
      return (*_data)[_i];
    }

  

    ByteSequence*& _data;

  private:
    ByteSequence_out();
    ByteSequence_out& operator=(const ByteSequence_var&);
  };


};

class _objref_ServerConfigHandler :
  public virtual ::CORBA::Object,
  public virtual omniObjRef
{
public:
  ::CORBA::Boolean loadPlugin(const char* pluginId, const char* pluginName);
  ::CORBA::Boolean unloadPlugin(const char* pluginId);
  ::CORBA::Boolean set(const char* pluginId, const char* propertyName, const ::ServerConfigHandler::ByteSequence& value);
  ServerConfigHandler::ByteSequence* get(const char* pluginId, const char* propertyName);
  ServerConfigHandler::ByteSequence* exec(const char* pluginId, const char* taskName, const ::ServerConfigHandler::ByteSequence& argumentList);
  ServerConfigHandler::StringSequence* metaProperties(const char* pluginId);
  ServerConfigHandler::StringSequence* metaTasks(const char* pluginId);
  char* lastErrorString();
  ::CORBA::Boolean hasFailure();

  inline _objref_ServerConfigHandler()  { _PR_setobj(0); }  // nil
  _objref_ServerConfigHandler(omniIOR*, omniIdentity*);

protected:
  virtual ~_objref_ServerConfigHandler();

  
private:
  virtual void* _ptrToObjRef(const char*);

  _objref_ServerConfigHandler(const _objref_ServerConfigHandler&);
  _objref_ServerConfigHandler& operator = (const _objref_ServerConfigHandler&);
  // not implemented

  friend class ServerConfigHandler;
};

class _pof_ServerConfigHandler : public _OMNI_NS(proxyObjectFactory) {
public:
  inline _pof_ServerConfigHandler() : _OMNI_NS(proxyObjectFactory)(ServerConfigHandler::_PD_repoId) {}
  virtual ~_pof_ServerConfigHandler();

  virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
  virtual _CORBA_Boolean is_a(const char*) const;
};

class _impl_ServerConfigHandler :
  public virtual omniServant
{
public:
  virtual ~_impl_ServerConfigHandler();

  virtual ::CORBA::Boolean loadPlugin(const char* pluginId, const char* pluginName) = 0;
  virtual ::CORBA::Boolean unloadPlugin(const char* pluginId) = 0;
  virtual ::CORBA::Boolean set(const char* pluginId, const char* propertyName, const ::ServerConfigHandler::ByteSequence& value) = 0;
  virtual ServerConfigHandler::ByteSequence* get(const char* pluginId, const char* propertyName) = 0;
  virtual ServerConfigHandler::ByteSequence* exec(const char* pluginId, const char* taskName, const ::ServerConfigHandler::ByteSequence& argumentList) = 0;
  virtual ServerConfigHandler::StringSequence* metaProperties(const char* pluginId) = 0;
  virtual ServerConfigHandler::StringSequence* metaTasks(const char* pluginId) = 0;
  virtual char* lastErrorString() = 0;
  virtual ::CORBA::Boolean hasFailure() = 0;
  
public:  // Really protected, workaround for xlC
  virtual _CORBA_Boolean _dispatch(omniCallHandle&);

private:
  virtual void* _ptrToInterface(const char*);
  virtual const char* _mostDerivedRepoId();
  
};




class POA_ServerConfigHandler :
  public virtual _impl_ServerConfigHandler,
  public virtual ::PortableServer::ServantBase
{
public:
  virtual ~POA_ServerConfigHandler();

  inline ::ServerConfigHandler_ptr _this() {
    return (::ServerConfigHandler_ptr) _do_this(::ServerConfigHandler::_PD_repoId);
  }
};







#undef _core_attr
#undef _dyn_attr



inline void
ServerConfigHandler::_marshalObjRef(::ServerConfigHandler_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}




#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_ServerConfigHandler
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_ServerConfigHandler
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_ServerConfigHandler
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_ServerConfigHandler
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_ServerConfigHandler
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_ServerConfigHandler
#endif

#endif  // __ServerConfigHandler_hh__

